#!/bin/bash
set -x

echo "==> Base"

echo "==> libc6 issue workaround"
echo 'libc6 libraries/restart-without-asking boolean true' | sudo debconf-set-selections

function install_from_url {
  cd /tmp && {
    curl -sfLo "$${1}.zip" "$${2}"
    unzip -qq "$${1}.zip"
    sudo mv "$${1}" "/usr/local/bin/$${1}"
    sudo chmod +x "/usr/local/bin/$${1}"
    rm -rf "$${1}.zip"
  }
}


echo "--> Adding helper for IP retrieval"
sudo tee /etc/profile.d/ips.sh > /dev/null <<EOF
function private_ip {
  curl -s http://169.254.169.254/latest/meta-data/local-ipv4
}

function public_ip {
  curl -s http://169.254.169.254/latest/meta-data/public-ipv4
}
EOF
source /etc/profile.d/ips.sh

echo "--> Updating apt-cache"
ssh-apt update

echo "--> Adding Hashicorp repo"
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
 sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

echo "--> Installing common dependencies"
apt-get install -y \
  curl \
  nano \
  git \
  jq \
  unzip \
  vault-enterprise \
  terraform

  echo "--> Pulling Workshop Terraform Repo"
  git clone -b no_tfc https://github.com/GuyBarros/terraform-hcp-vault-dynamic-credentials-workshop.git

  echo "--> do first TF init to ensure cleanup script runs without fail"
  cd /root/terraform-hcp-vault-dynamic-credentials-workshop/
  terraform init

  sudo tee /root/terraform-hcp-vault-dynamic-credentials-workshop/terraform.tfvars > /dev/null <<EOF
  public_key = "$(cat /root/.ssh/id_rsa.pub)"

  # please remember to add HCP_CLIENT_SECRET to your enviroment variables
  host_access_ip = ["$(curl -sS 'https://api.ipify.org?format=json' | jq -r ."ip")/32"]

